# @package _global_
defaults:
  - _self_
  - paths: default
  - callbacks: default
  - extras: default
  - hydra: default
  - experiment: null ##指定实验的名称
##实验需要配置的参数
project_name: ???
checkpoint_monitor: null
##可选的参数
tags: ["dev", "lightning "]
checkpoint_every_n_train_steps: 5000
seed: null
resume_from_ckpt: null
callback_every_n_train_steps: 1000
##注释
#root_dir: ${oc.env:PROJECT_ROOT}：指定项目的根目录。它通过读取环境变量 PROJECT_ROOT 来获取根目录的路径。
# data_dir: ${paths.root_dir}/data/：数据目录的路径，它基于根目录（root_dir）并在其后添加 /data/ 来确定数据的存放位置。
# log_dir: ${paths.root_dir}/logs/：日志目录的路径，同样基于根目录，并在其后添加 /logs/ 用于存储日志文件。
# output_dir: ${hydra:runtime.output_dir}：输出目录的路径，由 Hydra 在运行时动态生成。通常用于存储运行过程中生成的各种文件，如检查点（ckpts）和指标等。
# work_dir: ${hydra:runtime.cwd}：工作目录的路径，由 Hydra 在运行时根据当前工作目录（current working directory）确定。

trainer:
  _target_: lightning.pytorch.trainer.Trainer
  accelerator: gpu
  # devices: cpu
  # num_nodes: 2
  devices: [0, 1, 2, 3, 4, 5, 6, 7]
  precision: bf16-mixed
  # strategy: deepspeed_stage_2
  strategy: ddp_find_unused_parameters_true
  min_epochs: 100000
  max_epochs: 10000000
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1
  enable_model_summary: true
  deterministic: False
  log_every_n_steps: 1
  accumulate_grad_batches: 1
  # gradient_clip_algorithm: value
  gradient_clip_val: 0.2

logger:
  wandb:
    _target_: lightning.pytorch.loggers.wandb.WandbLogger
    # name: "" # name of the run (normally generated by wandb)
    save_dir: "${paths.output_dir}"
    offline: True
    id: null # pass correct id to resume experiment!
    anonymous: null # enable anonymous logging
    log_model: False # upload lightning ckpts
    prefix: "" # a string to put at the beginning of metric keys
    # entity: "" # set to name of your wandb team
    tags: ${tags}
    name: ${now:%Y-%m-%d-%H-%M-%S}
    project: ${project_name}
  tensorboard:
    _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    save_dir: ${paths.output_dir}/tensorboard
    name: ${now:%Y-%m-%d-%H-%M-%S}
