defaults:
  - _self_
  - paths: default

  - hydra: unwrap
  - experiment: null ##指定实验的名称
##实验需要配置的参数
project_name: ???
experiment_ckpt_path: ???
output_path: ???
deepspeed: ???
export_ema: ???
callback_every_n_train_steps: ???
