# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: .
# path to logging directory
# log_dir:  /root/autodl-fs/logs/
log_dir:  ./logs/
# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}
# path to working directory
work_dir: ${hydra:runtime.cwd}
##注释
#root_dir: ${oc.env:PROJECT_ROOT}：指定项目的根目录。它通过读取环境变量 PROJECT_ROOT 来获取根目录的路径。
# data_dir: ${paths.root_dir}/data/：数据目录的路径，它基于根目录（root_dir）并在其后添加 /data/ 来确定数据的存放位置。
# log_dir: ${paths.root_dir}/logs/：日志目录的路径，同样基于根目录，并在其后添加 /logs/ 用于存储日志文件。
# output_dir: ${hydra:runtime.output_dir}：输出目录的路径，由 Hydra 在运行时动态生成。通常用于存储运行过程中生成的各种文件，如检查点（ckpts）和指标等。
# work_dir: ${hydra:runtime.cwd}：工作目录的路径，由 Hydra 在运行时根据当前工作目录（current working directory）确定。
